[package]
name = "lufa-models"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
chrono-tz = "0.9.0"
rust_decimal = "1.35.0"
serde = { version = "1.0.201", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.117"
