[package]
name = "lufa-models"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
chrono-tz = "0.9.0"
rust_decimal = "1.35.0"
rusty-money = "0.4.1"
serde = { version = "1.0.201", features = ["derive"] }
serde-aux = "4.5.0"
uom = "0.36.0"

[dev-dependencies]
serde_json = "1.0.117"
